### ISSUE TITLE
Improve formatting of help content

### ISSUE THREAD

**Issue by msiism** [phil294/tkbash#10]
Could you provide better formatting for the help content? It's kind of a pain to read. Restricting output lines to a maximum of 80 columns should solve this.

Also, using `\t` to justify the text is problematic. It will break things if you pipe `tkbash --help` to `less`, for example.

Thanks!

**Comment by phil294** [comment]
Oh wow, how did I not see this? Sorry, somehow missed the notification. Your suggestion makes a lot of sense, I commited the changes. If you do not like it, feel free to reopen/comment or make a pull request.
